[project]
name = "linguamemoir"
version = "0.1.0"
description = "نظام إدارة لغات"
authors = ["Mostafa Ayman <email@example.com>"]
requires-python = ">=3.11"

[tool.poetry.dependencies]
python = ">=3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
