"""Initial migration

Revision ID: 37688b8cc053
Revises: 
Create Date: 2025-09-12 21:47:38.124063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37688b8cc053'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('product_sku', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.drop_column('product_sku')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
